id: medcom.fhir.dk.document
canonical: http://medcomfhir.dk/ig/document
name: MedComDocument
title: DK MedCom Document
description: The DK MedCom Document IG
status: active # draft | active | retired | unknown
version: 2.0.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://www.medcom.dk
  email: fhir@medcom.dk

dependencies:
  medcom.fhir.dk.xdsmetadata: 1.0.1
  medcom.fhir.dk.terminology: 2.0.2
  medcom.fhir.dk.core: 4.0.0
  hl7.fhir.dk.core: 3.5.0
  hl7.fhir.extensions.r5: 4.0.1
  ihe.iti.mhd: 4.2.3

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true
  show-inherited-invariants: false
  special-url: [urn:oid:1.2.208.184.100.9, urn:oid:2.16.840.1.113883.6.96, urn:oid:2.16.840.1.113883.6.1, urn:oid:1.2.208.184.100.1, urn:oid:1.2.208.176.2.4, urn:oid:1.2.208.176.2.1, urn:oid:1.2.208.176.7.3.1, urn:oid:1.2.208.184.100.10, urn:oid:1.2.208.176.8.1, urn:oid:2.16.840.1.113883.6.121, urn:oid:2.16.840.1.113883.5.79]

menu:
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html
    Profiling unstructured content: unstructuredclinicalcontent.html

instanceOptions:
  manualSliceOrdering: true # true | false